name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: requirements
      run: apt-get install libncurses-dev

    - name: build
      run: make
      
    - name: run
      run: ./cube -mi 5
